name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the bitfusion-device-plugin
      run: docker build -t docker.io/bitfusiondeviceplugin/bitfusion-device-plugin:0.3 -f bitfusion_device_plugin/device-plugin/build/Dockerfile .
